### PR TITLE
feat: `form` element for testing

### LINKED ISSUE #1: `form` elements could help developers see behavior of different types of `vh`s

### PR DESCRIPTION
**Pull request by hirehamir**
closes #1.

### CODE REVIEW

**Comment by hirehamir** [comment]
# Without this change

image

**Comment by hirehamir** [comment]
# With this change

image

**Comment by hirehamir** [comment]
Any reason in particular you decided to close this?

**Comment by kevin-powell** [comment]
The virtual keyboard doesn't impact dvh. If it did, I'd keep it, but it's only the UI elements that come and go while scrolling that have an impact, so having the form doesn't have any impact on how the units work.

**Pull request closed without merging**
